package com.jianma.zeus.model;
// Generated 2018-7-16 16:41:26 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Assignment generated by hbm2java
 */
@Entity
@Table(name = "assignment", catalog = "Zeus")
public class Assignment implements java.io.Serializable {

	private Integer id;
	private int userId;
	private int curriculumId;
	private String name;
	private boolean valid;
	private Date insertAt;
	private Date updateAt;

	public Assignment() {
	}

	public Assignment(int userId, int curriculumId, String name, boolean valid, Date insertAt) {
		this.userId = userId;
		this.curriculumId = curriculumId;
		this.name = name;
		this.valid = valid;
		this.insertAt = insertAt;
	}

	public Assignment(int userId, int curriculumId, String name, boolean valid, Date insertAt, Date updateAt) {
		this.userId = userId;
		this.curriculumId = curriculumId;
		this.name = name;
		this.valid = valid;
		this.insertAt = insertAt;
		this.updateAt = updateAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "curriculumId", nullable = false)
	public int getCurriculumId() {
		return this.curriculumId;
	}

	public void setCurriculumId(int curriculumId) {
		this.curriculumId = curriculumId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_at", nullable = false, length = 19)
	public Date getInsertAt() {
		return this.insertAt;
	}

	public void setInsertAt(Date insertAt) {
		this.insertAt = insertAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

}
