package com.jianma.zeus.model;
// Generated 2018-7-16 16:55:53 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag", catalog = "Zeus")
public class Tag implements java.io.Serializable {

	private Integer id;
	private int assignmentId;
	private String tagName;
	private Date insertAt;

	public Tag() {
	}

	public Tag(int assignmentId, String tagName, Date insertAt) {
		this.assignmentId = assignmentId;
		this.tagName = tagName;
		this.insertAt = insertAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "assignmentId", nullable = false)
	public int getAssignmentId() {
		return this.assignmentId;
	}

	public void setAssignmentId(int assignmentId) {
		this.assignmentId = assignmentId;
	}

	@Column(name = "tagName", nullable = false, length = 10)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_at", nullable = true, length = 19)
	public Date getInsertAt() {
		return this.insertAt;
	}

	public void setInsertAt(Date insertAt) {
		this.insertAt = insertAt;
	}

}
